require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - spec/rails_not_founder_dummy/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
